name: FFmpeg Clip

on:
  workflow_dispatch:
    inputs:
      videoUrl:
        description: 'YouTube Video URL'
        required: true
      startTime:
        description: 'Start time in seconds'
        required: true
      endTime:
        description: 'End time in seconds'
        required: true
      fileName:
        description: 'Output filename'
        required: true

jobs:
  clip:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get install -y ffmpeg bc
          pip install -U yt-dlp

      - name: Download and Clip Video
        run: |
          DURATION=$(echo "${{ github.event.inputs.endTime }} - ${{ github.event.inputs.startTime }}" | bc)
          yt-dlp \
            --no-check-certificate \
            --add-header "User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36" \
            -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" \
            --merge-output-format mp4 \
            -o "input.mp4" \
            "${{ github.event.inputs.videoUrl }}"
          ffmpeg -i input.mp4 \
            -ss ${{ github.event.inputs.startTime }} \
            -t $DURATION \
            -vf "scale=1080:1920:force_original_aspect_ratio=decrease,pad=1080:1920:(ow-iw)/2:(oh-ih)/2" \
            -c:v libx264 -c:a aac -preset fast \
            "${{ github.event.inputs.fileName }}.mp4"

      - name: Upload to Google Drive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.DRIVEKI }}
          filename: "${{ github.event.inputs.fileName }}.mp4"
          folderId: ${{ secrets.DRIVEFOLDER2 }}
          overwrite: "true"
